In [174]:
import pandas as pd
import requests
import numpy as np

In [177]:
import fastquant as fq

In [60]:
from pandas_datareader import data as web

In [105]:
url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"
htm = requests.get(url).content
data = pd.read_html(htm)

ValueError: No tables found

In [106]:
df = data[-1]

In [103]:
df.replace(to_replace =np.nan,value=0, inplace=True)

In [104]:
df[df["Symbol"] != 0]

,Rank,Name,Symbol,Market Cap,Price,Circulating Supply,Volume(24h),% 1h,% 24h,% 7d,...,Unnamed: 991,Unnamed: 992,Unnamed: 993,Unnamed: 994,Unnamed: 995,Unnamed: 996,Unnamed: 997,Unnamed: 998,Unnamed: 999,Unnamed: 1000
0,1.0,BTCBitcoin,BTC,"$1.15T$1,147,682,484,548","$60,852.91","18,859,943 BTC","$31,605,395,990",0.50%,-1.08%,0.61%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,ETHEthereum,ETH,"$503.31B$503,307,803,286","$4,259.79","118,153,082 ETH","$17,350,405,051",0.94%,-1.12%,5.53%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.0,BNBBinance Coin,BNB,"$86.41B$86,405,902,582",$518.02,"166,801,148 BNB *","$2,122,548,658",0.79%,-0.89%,8.93%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.0,USDTTether,USDT,"$70.32B$70,320,215,985",$1.00,"70,260,109,912 USDT *","$94,347,154,147",0.00%,0.01%,0.05%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,ADACardano,ADA,"$65.19B$65,194,620,378",$1.96,"33,271,319,193 ADA","$2,551,294,406",0.59%,-0.70%,-7.69%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6.0,SOLSolana,SOL,"$59.35B$59,347,303,340",$197.02,"301,230,673 SOL *","$2,359,572,551",0.19%,1.87%,3.11%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7.0,XRPXRP,XRP,"$51.50B$51,497,891,262",$1.10,"47,015,237,181 XRP *","$4,375,560,868",0.68%,1.21%,1.24%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8.0,DOTPolkadot,DOT,"$41.94B$41,944,105,557",$42.47,"987,579,315 DOT *","$1,257,604,270",0.60%,-1.17%,0.34%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9.0,SHIBSHIBA INU,SHIB,"$35.58B$35,575,372,575",$0.00006479,"549,095,509,738,353 SHIB *","$8,528,047,542",-3.98%,-7.96%,61.99%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10.0,DOGEDogecoin,DOGE,"$34.82B$34,819,336,010",$0.264,"131,916,121,102 DOGE","$3,230,206,534",1.61%,-3.22%,2.80%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,11.0,USDCUSD Coin,USDC,"$33.16B$33,158,680,658",$1.00,"33,155,189,646 USDC *","$4,252,956,266",0.00%,-0.03%,-0.02%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12.0,LUNATerra,LUNA,"$17.01B$17,008,210,596",$42.45,"400,688,103 LUNA *","$550,346,150",0.67%,-2.40%,4.14%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,13.0,UNIUniswap,UNI,"$15.48B$15,479,096,742",$24.66,"627,596,089 UNI *","$218,112,416",0.57%,-0.37%,-4.40%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,14.0,AVAXAvalanche,AVAX,"$13.91B$13,912,483,093",$63.16,"220,286,577 AVAX *","$375,185,147",1.15%,1.17%,-1.08%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,15.0,WBTCWrapped Bitcoin,WBTC,"$13.93B$13,932,536,904","$60,904.03","228,762 WBTC *","$327,236,569",0.58%,-1.01%,0.64%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,16.0,LINKChainlink,LINK,"$13.69B$13,691,512,473",$29.60,"462,509,554 LINK *","$897,034,251",0.97%,-1.14%,-0.88%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,17.0,BUSDBinance USD,BUSD,"$13.62B$13,622,988,522",$1.00,"13,619,701,327 BUSD *","$8,183,800,751",0.01%,-0.03%,0.00%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18.0,LTCLitecoin,LTC,"$13.19B$13,190,687,632",$191.52,"68,871,908 LTC","$2,149,819,665",1.13%,-0.08%,1.12%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,19.0,MATICPolygon,MATIC,"$12.70B$12,696,117,982",$1.87,"6,783,681,381 MATIC *","$1,559,043,200",2.05%,-1.57%,19.29%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,20.0,ALGOAlgorand,ALGO,"$11.42B$11,421,976,794",$1.84,"6,193,836,280 ALGO *","$295,603,043",2.46%,1.50%,0.94%,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [118]:
key = "50060c79-1e6c-46b9-85ae-2ee234132bf5"
api_url = f'https://pro-api.coinmarketcap.com/v1/cryptocurrency/map&API_KEY={key}'
raw = requests.get(api_url).content

In [119]:
raw

b'{\n    "statusCode": 404,\n    "error": "Not Found",\n    "message": "Not Found"\n}'

In [41]:
df

,name,market_cap,fd_market_cap,last,available_coins,total_coins,volume,returns
0,Bitcoin,1141.947B,1271.531B,60549.10,18.860M,21.000M,32.336B,-2.16%
1,Ethereum,498.325B,498.325B,4217.66,118.152M,118.152M,17.408B,-2.44%
2,Binance Coin,85.580B,85.580B,513.07,166.801M,166.801M,2.118B,-2.90%
3,Tether,70.316B,71.415B,1.00,70.260B,71.358B,95.906B,0.03%
4,Cardano,64.789B,87.631B,1.95,33.270B,45.000B,2.569B,-0.48%
...,...,...,...,...,...,...,...,...
145,Jasmy,543.489M,5.715B,0.11,4.755B,50.000B,109.360M,-0.65%
146,Polymath,529.688M,695.404M,0.70,761.699M,1.000B,49.970M,-2.77%
147,Factom,523.395M,934.030M,1.56,336.217M,600.000M,118.367M,-2.84%
148,Reserve Rights,518.070M,3.937B,0.04,13.160B,100.000B,89.964M,7.85%
149,Ocean Protocol,517.118M,1.189B,0.84,613.099M,1.410B,57.346M,4.60%

AttributeError: 'list' object has no attribute 'DataReader'

In [127]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'500',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': f'{key}',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  ## print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
    print(e)

In [141]:
df = pd.DataFrame(data["data"])

In [143]:
tickers = df["symbol"]

In [178]:
tickers.value_counts()

PAC      1
DEGO     1
TLOS     1
SNL      1
CVC      1
        ..
MOB      1
BZRX     1
STEEM    1
NANO     1
IQ       1
Name: symbol, Length: 500, dtype: int64

In [181]:
fq.get_crypto_data(f"BTC/USDT", start_date="2020-1-1", end_date="2020-10-1")

                open      high       low     close        volume
dt
2020-01-02   7200.77   7212.50   6924.74   6965.71  31951.483932
2020-01-03   6965.49   7405.00   6871.04   7344.96  68428.500451
2020-01-04   7345.00   7404.00   7272.21   7354.11  29987.974977
2020-01-05   7354.19   7495.00   7318.00   7358.75  38331.085604
2020-01-06   7357.64   7795.34   7346.76   7758.00  54635.695316
...              ...       ...       ...       ...           ...
2020-09-27  10728.59  10799.00  10594.82  10774.25  30549.483253
2020-09-28  10774.26  10950.00  10626.00  10696.12  50095.251734
2020-09-29  10696.11  10867.54  10635.87  10840.48  41874.898399
2020-09-30  10840.58  10849.34  10665.13  10776.59  39596.027322
2020-10-01  10776.59  10920.00  10437.00  10619.13  60866.332893

[274 rows x 5 columns]

In [166]:
del coins

In [184]:
tickers

0       BTC
1       ETH
2       BNB
3      USDT
4       ADA
       ...
495    WOZX
496     PAC
497     MTV
498     WTC
499    RMRK
Name: symbol, Length: 500, dtype: object

In [185]:
passed = []
failed = []
for t in tickers:
    try:
        data = fq.get_crypto_data(f"{t}/USDT", start_date="2020-1-1",end_date= "2021-10-1")["close"]
    except:
        failed.append(t)

In [172]:
coins = pd.DataFrame()

In [160]:
web.DataReader(f"{tickers[0]}-USD", data_source="yahoo", start = "2011-1-1")

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2014-09-16,468.174011,452.421997,465.864014,457.334015,2.105680e+07,457.334015
2014-09-17,456.859985,413.104004,456.859985,424.440002,3.448320e+07,424.440002
2014-09-18,427.834991,384.532013,424.102997,394.795990,3.791970e+07,394.795990
2014-09-19,423.295990,389.882996,394.673004,408.903992,3.686360e+07,408.903992
2014-09-20,412.425995,393.181000,408.084991,398.821014,2.658010e+07,398.821014
...,...,...,...,...,...,...
2021-10-26,61435.183594,58208.187500,60352.000000,58482.386719,4.365708e+10,58482.386719
2021-10-27,62128.632812,58206.917969,58470.730469,60622.136719,4.525708e+10,60622.136719
2021-10-28,62927.609375,60329.964844,60624.871094,62227.964844,3.685688e+10,62227.964844
2021-10-29,62330.144531,60918.386719,62239.363281,61888.832031,3.215794e+10,61888.832031
2021-10-31,62386.964844,60211.023438,62166.972656,60653.886719,3.155647e+10,60653.886719

In [170]:
tickers.nunique()

500

In [173]:
for t in tickers[0:12]:
    coins[t] = web.DataReader(f"{t}-USD", data_source="yahoo", start = "2020-1-1")["Adj Close"]

RemoteDataError: No data fetched for symbol SOL-USD using YahooDailyReader

In [151]:
##coins.to_csv("resources/coins_11-31-2021")

In [158]:
coins

,BTC,ETH,BNB,USDT,ADA,SOL,XRP,DOT,SHIB,DOGE,...,RBN,DEGO,SSV,LDO,BEPRO,WOZX,PAC,MTV,WTC,RMRK
Date,,,,,,,,,,,,,,,,,,,,,
2014-09-16,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,...,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015,457.334015
2014-09-17,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,...,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002,424.440002
2014-09-18,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,...,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990,394.795990
2014-09-19,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,...,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992,408.903992
2014-09-20,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,...,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014,398.821014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-26,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,...,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719,58482.386719
2021-10-27,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,...,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719,60622.136719
2021-10-28,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,...,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844,62227.964844
2021-10-29,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,...,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031,61888.832031
2021-10-31,60610.488281,60610.488281,60610.488281,60610.488281,60610.488281,60610.488281,60610.488281,60610.488281,60610.488281,60606.367188,...,60524.015625,60524.015625,60524.015625,60524.015625,60524.015625,60524.015625,60524.015625,60524.015625,60524.015625,60524.015625